### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by ubaidfayyaz** [Fazail333/Booths_Multiplier#3]
Please add makefile to compile for vivado's xsim and verilator.

**Comment by Shanzaywasim** [comment]
@ubaidfayyaz Sir, Do we need to write a .tcl script for the simulation on xsim?

**Comment by ubaidfayyaz** [comment]
Nope. A make file.

https://www.gnu.org/software/make/

When I write `make vivado` it should simulate on `xsim`. When I write `make verilator` it should simulate on `verilator`.

**Comment by Shanzaywasim** [comment]
Noted

**Comment by Fazail333** [comment]
@ubaidfayyaz Sir, we have successfully completed the Makefile. Kindly review and confirm its accuracy.
