### ISSUE TITLE
Add randomization in the testbench.

### ISSUE THREAD

**Issue by ubaidfayyaz** [Fazail333/Booths_Multiplier#4]
Currently, the testbench tests the module for a couple of inputs only. You should randomize the inputs and verify the output of the RTL modules against a reference model. The reference model can be a simple SystemVerilog function with `*` operator.

**Comment by Fazail333** [comment]
@ubaidfayyaz Sir, just wanted to let you know that we've finished the Verilator and XSIM testbenches with random inputs. Could you please take a moment to review them? Thanks a lot!
